title: Blackbright
email: samuelson@blackbright.gq
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/Blab-test" # the subpath of your site, e.g. /blog
url: "www.blackbright.gq" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

sass:
  sass_dir: assets/css
  style: compressed

branches:
  only:
    - gh-pages
